// Command gen-ts-fixture issues a deterministic Personhood credential with a
// fixed Ed25519 key and prints a JSON fixture the TypeScript SDK uses to prove
// cross-language verification interop (JCS canonicalization + Ed25519 +
// nullifier derivation).
//
// Regenerate with:
//
//	cd tools/gen-ts-fixture && GOWORK=off go run . > ../../sdk/typescript/test/fixtures/credential.json
package main

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/sagearbor/personhood/pkg/types"
	"github.com/sagearbor/personhood/src/credential"
	"github.com/sagearbor/personhood/src/policy"
)

func main() {
	// Deterministic key from a fixed 32-byte seed so the fixture is stable.
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i + 1)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	const issuerDID = types.DID("did:web:personhood.example")
	const holderDID = types.DID("did:web:holder.example")

	issuedAt := time.Date(2026, 6, 15, 11, 0, 0, 0, time.UTC)
	expiresAt := time.Date(2026, 9, 13, 11, 0, 0, 0, time.UTC)

	iss := credential.NewIssuer(issuerDID, "key-1", priv, "")
	anchor := "government-id-liveness"
	methods := []types.VerifiedMethod{
		{
			MethodID:          anchor,
			Strength:          90,
			VerifiedAt:        issuedAt,
			FreshnessLifetime: 90 * 24 * time.Hour,
			AttestationDigest: "deadbeefdeadbeef",
		},
		{
			MethodID:          "email",
			Strength:          12,
			VerifiedAt:        issuedAt.Add(-1 * time.Hour),
			FreshnessLifetime: 30 * 24 * time.Hour,
			AttestationDigest: "cafebabecafebabe",
		},
	}
	binding := &types.NullifierBinding{
		Commitment: "0a1b2c3d4e5f60718293a4b5c6d7e8f9",
		Curve:      "bn254",
		Scheme:     "pedersen-v1",
	}

	cred, err := iss.Issue(holderDID, methods, &anchor, binding, issuedAt, expiresAt, nil)
	if err != nil {
		fail(err)
	}

	// Compute the nullifier the TS SDK must reproduce for this context tag.
	const contextTag = "openline/suffrage/vote/election-42"
	nullifier, err := policy.DeriveNullifier(*binding, contextTag)
	if err != nil {
		fail(err)
	}

	credJSON, err := json.Marshal(cred)
	if err != nil {
		fail(err)
	}

	fixture := map[string]any{
		"comment":            "Generated by tools/gen-ts-fixture. Do not edit by hand.",
		"issuerDID":          issuerDID,
		"issuerPublicKeyB64": base64.StdEncoding.EncodeToString(pub),
		// credentialJSON is the exact bytes the issuer signed over (minus proof);
		// the TS SDK must canonicalize this same text.
		"credentialJSON":     string(credJSON),
		"nowRFC3339":         "2026-06-15T12:00:00Z",
		"nullifierContext":   contextTag,
		"expectedNullifier":  nullifier,
	}
	out, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		fail(err)
	}
	fmt.Println(string(out))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-ts-fixture:", err)
	os.Exit(1)
}
