//go:build sendgrid

// Package-level build tag: this file is only compiled into binaries built
// with `go build -tags sendgrid` (or `-tags 'sendgrid twilio'`). Without the
// tag, sendgrid_sender_disabled.go provides a NewSendGridSender stub that
// returns an error, and the default Sender is the LogSender shipped in
// sender.go. See docs/02-methods.md for the env-var matrix.

package email

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

// SendGridAPIURL is the v3 mail-send endpoint.
const SendGridAPIURL = "https://api.sendgrid.com/v3/mail/send"

// SendGridSender delivers magic-link emails through SendGrid's v3 Mail Send
// API.
//
// Safe for concurrent use. Uses plain net/http to avoid pulling in the
// SendGrid Go SDK (which would also pull in opencensus + opentracing).
type SendGridSender struct {
	APIKey      string
	FromAddress string
	FromName    string

	// HTTPClient is the underlying client. If nil, a client with a 15s
	// timeout is used.
	HTTPClient *http.Client

	// Endpoint overrides SendGridAPIURL. Used by tests to point at a
	// httptest server.
	Endpoint string
}

// NewSendGridSender constructs a SendGridSender. apiKey and fromAddress are
// required; fromName may be empty.
func NewSendGridSender(apiKey, fromAddress, fromName string) (*SendGridSender, error) {
	if strings.TrimSpace(apiKey) == "" {
		return nil, errors.New("email: SendGrid API key is required")
	}
	if strings.TrimSpace(fromAddress) == "" {
		return nil, errors.New("email: SendGrid From address is required")
	}
	return &SendGridSender{
		APIKey:      apiKey,
		FromAddress: fromAddress,
		FromName:    fromName,
		HTTPClient:  &http.Client{Timeout: 15 * time.Second},
		Endpoint:    SendGridAPIURL,
	}, nil
}

// Send implements Sender by POSTing a v3 mail-send request to SendGrid.
//
// On any HTTP failure or non-2xx response, an error is returned and the
// caller (Method.BeginCeremony) will invalidate the just-stored token so the
// user can retry.
func (s *SendGridSender) Send(ctx context.Context, to string, subject string, magicLinkURL string) error {
	if s == nil {
		return errors.New("email: nil SendGridSender")
	}
	endpoint := s.Endpoint
	if endpoint == "" {
		endpoint = SendGridAPIURL
	}

	plain := fmt.Sprintf(
		"Tap the link to confirm your email for Personhood enrollment:\n\n%s\n\n"+
			"This link expires in 15 minutes. If you did not request it, you can ignore this email.",
		magicLinkURL,
	)
	// html/template is overkill for a one-link transactional body; we build
	// the HTML inline and rely on the fact that magicLinkURL is generated by
	// the server (never user-supplied). Even so, we URL-quote the href to
	// defend against any unexpected characters.
	htmlBody := fmt.Sprintf(
		`<!doctype html><html><body style="font-family:system-ui,sans-serif;line-height:1.5;color:#0f1115">`+
			`<p>Tap the button below to confirm your email for Personhood enrollment.</p>`+
			`<p><a href=%q style="display:inline-block;padding:10px 16px;border-radius:8px;background:#0f1115;color:#fff;text-decoration:none">Confirm email</a></p>`+
			`<p style="color:#6b7280;font-size:14px">Or open this link directly: <a href=%q>%s</a></p>`+
			`<p style="color:#6b7280;font-size:14px">This link expires in 15 minutes. If you did not request it, you can ignore this email.</p>`+
			`</body></html>`,
		magicLinkURL, magicLinkURL, magicLinkURL,
	)

	payload := sendGridRequest{
		Personalizations: []sendGridPersonalization{
			{To: []sendGridAddress{{Email: to}}},
		},
		From: sendGridAddress{Email: s.FromAddress, Name: s.FromName},
		Subject: subject,
		Content: []sendGridContent{
			{Type: "text/plain", Value: plain},
			{Type: "text/html", Value: htmlBody},
		},
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("email/sendgrid: marshal: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("email/sendgrid: build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+s.APIKey)
	req.Header.Set("Content-Type", "application/json")

	client := s.HTTPClient
	if client == nil {
		client = http.DefaultClient
	}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("email/sendgrid: post: %w", err)
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))

	// SendGrid returns 202 Accepted for successful sends. Other 2xx is also OK.
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("email/sendgrid: status %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}

// SendGridSenderEnabled reports whether the binary was built with the
// sendgrid build tag. Always true in this build-tagged file; the disabled
// twin returns false.
func SendGridSenderEnabled() bool { return true }

// realSenderFromEnv is consumed by NewSenderFromEnv (factory.go). In the
// sendgrid build it inspects SENDGRID_API_KEY + SENDGRID_FROM and returns a
// configured SendGridSender; if either is empty it returns nil so the
// factory falls back to LogSender.
func realSenderFromEnv() Sender {
	apiKey := os.Getenv("SENDGRID_API_KEY")
	from := os.Getenv("SENDGRID_FROM")
	if apiKey == "" || from == "" {
		return nil
	}
	s, err := NewSendGridSender(apiKey, from, os.Getenv("SENDGRID_FROM_NAME"))
	if err != nil {
		log.Printf("email/sendgrid: %v; falling back to LogSender", err)
		return nil
	}
	return s
}

// ---------------------------------------------------------------------------
// SendGrid wire types (kept package-private; not part of the public API)
// ---------------------------------------------------------------------------

type sendGridRequest struct {
	Personalizations []sendGridPersonalization `json:"personalizations"`
	From             sendGridAddress           `json:"from"`
	Subject          string                    `json:"subject"`
	Content          []sendGridContent         `json:"content"`
}

type sendGridPersonalization struct {
	To []sendGridAddress `json:"to"`
}

type sendGridAddress struct {
	Email string `json:"email"`
	Name  string `json:"name,omitempty"`
}

type sendGridContent struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}
